FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Build the binary
RUN go build -o enrichmentService cmd/enrichment/main.go

# Run
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/enrichmentService .

CMD ["./enrichmentService"]
